# Generated by Django 3.0.3 on 2020-03-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=150)),
                ('Direccion', models.CharField(max_length=100)),
                ('Telefono', models.PositiveIntegerField(blank=True, null=True)),
                ('Nit', models.PositiveIntegerField(blank=True, null=True)),
                ('Particular', models.BooleanField(blank=True, default=False, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
