# Generated by Django 3.0.3 on 2020-07-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precio',
            name='Elemento',
        ),
        migrations.RemoveField(
            model_name='precio',
            name='Precio',
        ),
        migrations.AddField(
            model_name='precio',
            name='Cobre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='precio',
            name='Estanio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='precio',
            name='H2O',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='precio',
            name='Plata',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='precio',
            name='Plomo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='precio',
            name='Zinc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
