# Generated by Django 3.0.3 on 2020-07-18 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20200711_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='Antimonio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='Arsenico',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='Hierro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='precio',
            name='Cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente'),
        ),
    ]
