# Generated by Django 3.0.3 on 2020-03-17 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_producto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Elemento',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resultado', models.FloatField()),
                ('estado', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('Elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Elemento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Producto')),
            ],
        ),
    ]
