# Generated by Django 3.0.3 on 2020-03-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_auto_20200317_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Caracteristicas',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Nit',
            field=models.PositiveIntegerField(blank=True, help_text='Opcional', null=True),
        ),
    ]
