# Generated by Django 3.0.3 on 2020-08-08 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_producto_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Nit',
            field=models.BigIntegerField(blank=True, help_text='Opcional', null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
