# Generated by Django 3.0.3 on 2020-08-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_auto_20200807_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Correo',
            field=models.EmailField(blank=True, help_text='Opcional', max_length=254, null=True),
        ),
    ]
