# Generated by Django 3.0.3 on 2020-06-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_auto_20200319_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Telefono',
            field=models.PositiveIntegerField(blank=True, help_text='Opcional', null=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='Abreviatura',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='Nombre_del_Elemento',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
