# Generated by Django 3.0.3 on 2020-07-03 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cliente', '0008_auto_20200613_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='estado',
            field=models.BooleanField(default=True, help_text='Desactive esta casilla para dar de baja este elemento'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.BooleanField(default=True, help_text='Desactive esta casilla para dar de baja este producto'),
        ),
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Codigo'),
        ),
    ]
